name: Trigger Downstream

on:
  push:
    tags:
      - "v*"

permissions:
  actions: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - kamalyes/go-logger
          - kamalyes/go-cachex
          - kamalyes/go-config
          - kamalyes/go-i18n
          - kamalyes/go-natsx
          - kamalyes/go-ossx
          - kamalyes/go-pbmo
          - kamalyes/go-sqlbuilder
          - kamalyes/go-swagger
          - kamalyes/go-wsc
          - kamalyes/go-logger-adapter
          - kamalyes/go-namesilo
          - kamalyes/go-phantom
          - kamalyes/go-casbin
          - kamalyes/go-casbin-gorm-adapter
          - kamalyes/go-casbin-kafka-adapter
          - kamalyes/go-casbin-nats-adapter
          - kamalyes/go-casbin-redis-adapter
          - kamalyes/go-scope-provider
    steps:
      - name: Dispatch to ${{ matrix.repo }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_GPA_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: upstream-updated
          client-payload: >-
            {"module": "github.com/kamalyes/go-toolbox", "version": "${{ github.ref_name }}", "sha": "${{ github.sha }}"}
